### ISSUE TITLE
请问使用场景是什么呢?

### ISSUE THREAD

**Issue by xjdata** [dvajs/dva-model-extend#1]
安装后, 按照test 自己扩展了下已有model. 但是远程请求部分的 service.update 等等实际地址无法替换.只能是一个model集成另一个model的属性吗?

水平很菜,可能提问很初级,还望见谅. 谢谢.

**Comment by benjycui** [comment]
你这种使用场景，应该配合工厂方法：

```
createModel(updateService) {
  return {
    ...
    effects: {
      update() {
        // use updateService here.
      }
    }
  };
}
```

**Comment by benjycui** [comment]
本质就是把继承这个特性引进 dva model

**Comment by longzhaobi** [comment]
这个issue解决了我的问题，真的是大爱啊！一直到纠结如何共用service..
