### ISSUE TITLE
覆盖的话，可以报一个警告吗

### ISSUE THREAD

**Issue by yangbin1994** [dvajs/dva-model-extend#2]
这个项目真的好用，赞~
我拿这个工具不仅作为继承方式，也用来组织model，有个担心就是属性被覆盖了~

**Comment by yangbin1994** [comment]
可以的话 我可以提pr

**Comment by benjycui** [comment]
> 可以的话 我可以提pr

👍

**Comment by yangbin1994** [comment]
https://github.com/dvajs/dva-model-extend/pull/3
我觉得model的粒度可以再小一点，所以尝试写了一个[dva-model-combo](https://github.com/yangbin1994/dva-model-combo)项目基于dva-model-extend搭建的~，望指教。
ps：[ava](https://github.com/avajs/ava)这个测试框架挺好用的很简洁，小小的推荐一下~

**Comment by yangbin1994** [comment]
之前滥用了redux，极端到管理组件的所有state都放到外部管理，徒增代码量，dva-model-xxx的model管理工具对我来说好像是潘多拉的盒子一样。。。

**Comment by yangbin1994** [comment]
要道个歉，之前想当然的将namespace对应到routeModel，实际开发中routeModel是由更多的container组成，这个时候，就觉得应该出现一个粒度来划分model到container上，虽然实现了，但是写代码时候发现了一个问题，如果严格按照我的目标那么model的层级会很深，其实只要跳出namespace和routeModel对应的这个怪圈，model的父子关系完全可以由namespcae的命名来体现，这样的话dva-model-combo就没有必要了
