### ISSUE TITLE
是否支持react-native?

### ISSUE THREAD

**Issue by meyer-net** [dvajs/dva-model-extend#4]
今天在react-native下想使用该插件：
import modelExtend from 'dva-model-extend'

却报错：
![image](https://user-images.githubusercontent.com/16422453/31330810-79c5b742-ad12-11e7-8b92-dfbd66d9c9d4.png)

**Comment by benjycui** [comment]
这报错，应该是构建工具的问题。

**Comment by meyer-net** [comment]
我看了下源码的 package.json，有依赖 
"babel-plugin-transform-runtime": "^6.23.0",
"babel-preset-es2015": "^6.24.1",
两个包，于是手动安装了就没问题了。

按理说，npm安装时，应该依赖也同等装载进来才是。

**Comment by benjycui** [comment]
devDependencies
