### ISSUE TITLE
复用的model在使用effects时会有问题

### ISSUE THREAD

**Issue by hylin** [dvajs/dva-model-extend#5]
比如model B，和model C通过这个组件扩展自model A。

一个应用入口文件B会注册 model B，一个应用入口文件会注册model C，model A并不会被这两个应用直接注册，它只是用来定义B和C的共用部分。

model A里面有一个effects 叫fun1，它里面用select来取全局state的某一个属性test。

B和C都会用到这个个effects，运行阶段，select中的state是实际是包含当前注册的模型名，这里有个问题就是，运行阶段select中我无法知道当前模型的名字，也就是下面示例中我取state的值时，在B、C两个应用中，`模型命名空间`部分应该是不同，有什么办法可以在运行时知道当前的模型名称呢？

```
*fun1({ payload }, { call, put, select }) {
  cosnt test = select(state=>state.模型命名空间.test);
}
```

**Comment by benjycui** [comment]
```jsx
*fun1({ action }) {
  console.log(action);
  // extract namespace from action
}
```
